package org.example.mcoService.exception;

import lombok.Getter;

@Getter
public enum McoErrorCode {

    // Общие коды
    OPENAPI_PARTNER_API_INTERNAL_ERROR("OPENAPI_PARTNER_API_INTERNAL_ERROR", ErrorType.RETRYABLE),
    OPENAPI_PARTNER_API_PARTNER_DENY("OPENAPI_PARTNER_API_PARTNER_DENY", ErrorType.FATAL),
    OPENAPI_PARTNER_API_UNKNOWN_OPERATION("OPENAPI_PARTNER_API_UNKNOWN_OPERATION", ErrorType.FATAL),
    REQUEST_VALIDATION_ERROR("REQUEST_VALIDATION_ERROR", ErrorType.BUSINESS),
    USER_NOT_BOUND("USER_NOT_BOUND", ErrorType.BUSINESS),
    CONSENT_REQUIRED("CONSENT_REQUIRED", ErrorType.BUSINESS),

    // Регистрация
    OPENAPI_PARTNER_API_MAX_IMAGE_SIZE_EXCEEDED("OPENAPI_PARTNER_API_MAX_IMAGE_SIZE_EXCEEDED", ErrorType.BUSINESS),

    // Подключение пользователя
    PARTNER_NOT_FOUND("PARTNER_NOT_FOUND", ErrorType.FATAL),
    PARTNER_NOT_ACTIVE("PARTNER_NOT_ACTIVE", ErrorType.FATAL),
    DUPLICATE_REQUEST_ID("DUPLICATE_REQUEST_ID", ErrorType.BUSINESS),
    IDENTIFIER_ALREADY_BOUND("IDENTIFIER_ALREADY_BOUND", ErrorType.BUSINESS),
    BINDREQUEST_ALREADY_EXPIRED_DATE("BINDREQUEST_ALREADY_EXPIRED_DATE", ErrorType.BUSINESS),
    IDENTIFIER_FORMAT_VALIDATION_FAILED("IDENTIFIER_FORMAT_VALIDATION_FAILED", ErrorType.BUSINESS),
    PREVIOUS_REQUEST_ACTIVE("PREVIOUS_REQUEST_ACTIVE", ErrorType.BUSINESS),

    // ────────────── новые для PostBindPartner ──────────────
    IDENTIFIER_NOT_FOUND("IDENTIFIER_NOT_FOUND", ErrorType.BUSINESS),
    IDENTIFIER_INVALID("IDENTIFIER_INVALID", ErrorType.BUSINESS),
    IDENTIFIER_BLOCKED("IDENTIFIER_BLOCKED", ErrorType.BUSINESS),
    IDENTIFIER_TEMPORARILY_UNAVAILABLE("IDENTIFIER_TEMPORARILY_UNAVAILABLE", ErrorType.RETRYABLE),
    MAX_ACTIVE_REQUESTS_EXCEEDED("MAX_ACTIVE_REQUESTS_EXCEEDED", ErrorType.BUSINESS),
    PERMISSION_GROUP_INVALID("PERMISSION_GROUP_INVALID", ErrorType.BUSINESS),
    EXPIRED_AT_INVALID("EXPIRED_AT_INVALID", ErrorType.BUSINESS),
    REQUEST_ALREADY_EXISTS("REQUEST_ALREADY_EXISTS", ErrorType.BUSINESS),
    // ───────────────────────────────────────────────────────

    // Лента чеков
    RECEIPT_TAPE_BAD_MARKER_EXPIRED("RECEIPT_TAPE_BAD_MARKER_EXPIRED", ErrorType.RETRYABLE),
    RECEIPT_TAPE_BAD_MARKER("RECEIPT_TAPE_BAD_MARKER", ErrorType.RETRYABLE),

    // Оповещения
    IDENTIFIER_UNBOUND("IDENTIFIER_UNBOUND", ErrorType.BUSINESS),

    // Email
    EMAIL_ALREADY_BOUND("EMAIL_ALREADY_BOUND", ErrorType.BUSINESS),
    EMAIL_CONFIRMATION_EMAIL_ALREADY_EXISTS("EMAIL_CONFIRMATION_EMAIL_ALREADY_EXISTS", ErrorType.BUSINESS),
    EMAIL_CONFIRMATION_WRONG_EMAIL("EMAIL_CONFIRMATION_WRONG_EMAIL", ErrorType.BUSINESS),

    // Доверенные партнеры
    PERMISSION_DENY_ONLY_TRUSTED("PERMISSION_DENY_ONLY_TRUSTED", ErrorType.FATAL),
    INVALID_FORMAT_EMAIL("INVALID_FORMAT_EMAIL", ErrorType.BUSINESS),
    BINDING_NOT_FOUND("BINDING_NOT_FOUND", ErrorType.BUSINESS),

    // ────────────── специфичные для GetBindPartnerEvent ──────────────
    MARKER_INVALID("MARKER_INVALID", ErrorType.BUSINESS),
    MARKER_EXPIRED("MARKER_EXPIRED", ErrorType.BUSINESS),
    TOO_MANY_EVENTS("TOO_MANY_EVENTS", ErrorType.RETRYABLE),
    NO_EVENTS_AVAILABLE("NO_EVENTS_AVAILABLE", ErrorType.BUSINESS),

    // ────────────── специфичные для PostUnbindPartner ──────────────
    UNBIND_REASON_INVALID("UNBIND_REASON_INVALID", ErrorType.BUSINESS),
    IDENTIFIER_NOT_BOUND("IDENTIFIER_NOT_BOUND", ErrorType.BUSINESS),
    UNBIND_OPERATION_NOT_ALLOWED("UNBIND_OPERATION_NOT_ALLOWED", ErrorType.BUSINESS),
    UNBIND_ALREADY_IN_PROGRESS("UNBIND_ALREADY_IN_PROGRESS", ErrorType.RETRYABLE),

    // ────────────── специфичные для GetBindPartnerStatus ──────────────
    REQUEST_NOT_FOUND("REQUEST_NOT_FOUND", ErrorType.BUSINESS),
    INVALID_REQUEST_ID_FORMAT("INVALID_REQUEST_ID_FORMAT", ErrorType.BUSINESS),
    TOO_MANY_REQUEST_IDS("TOO_MANY_REQUEST_IDS", ErrorType.BUSINESS),
    PARTIAL_REQUESTS_NOT_FOUND("PARTIAL_REQUESTS_NOT_FOUND", ErrorType.BUSINESS),
    STATUS_RESPONSE_INCOMPLETE("STATUS_RESPONSE_INCOMPLETE", ErrorType.RETRYABLE),

    // ────────────── специфичные для GetReceiptsTape ──────────────
    RECEIPT_TAPE_ACCESS_DENIED("RECEIPT_TAPE_ACCESS_DENIED", ErrorType.FATAL),
    RECEIPT_TAPE_NO_ACCESS("RECEIPT_TAPE_NO_ACCESS", ErrorType.BUSINESS),
    RECEIPT_TAPE_MARKER_INVALID("RECEIPT_TAPE_MARKER_INVALID", ErrorType.BUSINESS),
    RECEIPT_TAPE_MARKER_EXPIRED("RECEIPT_TAPE_MARKER_EXPIRED", ErrorType.RETRYABLE),
    RECEIPT_TAPE_INTERNAL_ERROR("RECEIPT_TAPE_INTERNAL_ERROR", ErrorType.RETRYABLE),
    RECEIPT_TAPE_TOO_MANY_REQUESTS("RECEIPT_TAPE_TOO_MANY_REQUESTS", ErrorType.RETRYABLE),

    // ────────────── специфичные для PostPlatformRegistration ──────────────
    PARTNER_ALREADY_REGISTERED("PARTNER_ALREADY_REGISTERED", ErrorType.BUSINESS),
    INN_ALREADY_USED("INN_ALREADY_USED", ErrorType.BUSINESS),
    INN_INVALID("INN_INVALID", ErrorType.BUSINESS),
    INN_NOT_FOUND("INN_NOT_FOUND", ErrorType.BUSINESS),
    PHONE_INVALID("PHONE_INVALID", ErrorType.BUSINESS),
    LOGO_INVALID_FORMAT("LOGO_INVALID_FORMAT", ErrorType.BUSINESS),
    LOGO_TOO_LARGE("LOGO_TOO_LARGE", ErrorType.BUSINESS),
    LOGO_PROCESSING_ERROR("LOGO_PROCESSING_ERROR", ErrorType.RETRYABLE),
    TRANSITION_LINK_INVALID("TRANSITION_LINK_INVALID", ErrorType.BUSINESS),
    DESCRIPTION_TOO_LONG("DESCRIPTION_TOO_LONG", ErrorType.BUSINESS),
    NAME_INVALID("NAME_INVALID", ErrorType.BUSINESS),

    // ────────────── специфичные для GetUnboundPartner ──────────────
    MARKER_INVALID_UNBOUND("MARKER_INVALID_UNBOUND", ErrorType.BUSINESS),
    MARKER_EXPIRED_UNBOUND("MARKER_EXPIRED_UNBOUND", ErrorType.RETRYABLE),
    NO_UNBOUND_USERS("NO_UNBOUND_USERS", ErrorType.BUSINESS),
    UNBOUND_ACCESS_DENIED("UNBOUND_ACCESS_DENIED", ErrorType.FATAL),
    UNBOUND_TOO_MANY_REQUESTS("UNBOUND_TOO_MANY_REQUESTS", ErrorType.RETRYABLE),

    // ────────────── специфичные для PostNotification ──────────────
    NOTIFICATION_PERMISSION_DENIED("NOTIFICATION_PERMISSION_DENIED", ErrorType.BUSINESS),
    USER_IDENTIFIER_NOT_FOUND("USER_IDENTIFIER_NOT_FOUND", ErrorType.BUSINESS),
    USER_IDENTIFIER_UNBOUND("USER_IDENTIFIER_UNBOUND", ErrorType.BUSINESS),
    NOTIFICATION_CATEGORY_INVALID("NOTIFICATION_CATEGORY_INVALID", ErrorType.BUSINESS),
    NOTIFICATION_MESSAGE_TOO_LONG("NOTIFICATION_MESSAGE_TOO_LONG", ErrorType.BUSINESS),
    NOTIFICATION_SHORT_MESSAGE_TOO_LONG("NOTIFICATION_SHORT_MESSAGE_TOO_LONG", ErrorType.BUSINESS),
    EXTERNAL_ITEM_URL_INVALID("EXTERNAL_ITEM_URL_INVALID", ErrorType.BUSINESS),
    DUPLICATE_NOTIFICATION("DUPLICATE_NOTIFICATION", ErrorType.BUSINESS),
    NOTIFICATION_RATE_LIMIT_EXCEEDED("NOTIFICATION_RATE_LIMIT_EXCEEDED", ErrorType.RETRYABLE),
    NOTIFICATION_INTERNAL_ERROR("NOTIFICATION_INTERNAL_ERROR", ErrorType.RETRYABLE),

    // ────────────── специфичные для PostBindPartnerBatch ──────────────
    BATCH_TOO_LARGE("BATCH_TOO_LARGE", ErrorType.BUSINESS),
    BATCH_PARTIAL_ACCEPTED("BATCH_PARTIAL_ACCEPTED", ErrorType.BUSINESS),           // бизнес-ошибка, если часть принята, часть отклонена по валидации
    BATCH_REQUEST_ID_DUPLICATE("BATCH_REQUEST_ID_DUPLICATE", ErrorType.BUSINESS),
    BATCH_IDENTIFIER_INVALID("BATCH_IDENTIFIER_INVALID", ErrorType.BUSINESS),
    BATCH_TOO_MANY_INVALID_IDENTIFIERS("BATCH_TOO_MANY_INVALID_IDENTIFIERS", ErrorType.BUSINESS),
    BATCH_INTERNAL_PROCESSING_ERROR("BATCH_INTERNAL_PROCESSING_ERROR", ErrorType.RETRYABLE),

    UNKNOWN("UNKNOWN", ErrorType.FATAL);

    private final String code;
    private final ErrorType type;

    McoErrorCode(String code, ErrorType type) {
        this.code = code;
        this.type = type;
    }

    public static McoErrorCode fromCode(String code) {
        for (McoErrorCode errorCode : values()) {
            if (errorCode.code.equals(code)) {
                return errorCode;
            }
        }
        return UNKNOWN;
    }

    public enum ErrorType {
        RETRYABLE,
        BUSINESS,
        FATAL
    }
}